import io

path = "wp-stocks-manager.php"
content = io.open(path, encoding="utf-8").read()

old = (
    "    $is_us_symbol = (strpos($symbol, '.T') === false);\n"
    "    if ($is_us_symbol) {\n"
    "        $fmp = wp_stocks_fmp_get_ratios($symbol);\n"
    "        if ($fmp !== false) {\n"
    "            $result['per']            = $fmp['per'];\n"
    "            $result['pbr']            = $fmp['pbr'];\n"
    "            $result['eps']            = $fmp['eps'];\n"
    "            $result['profit_margin']  = $fmp['profit_margin'];\n"
    "            $result['dividend_yield'] = $fmp['dividend_yield'];\n"
    "            $result['peg_trailing']   = $fmp['peg_trailing'];\n"
    "            $result['peg']            = $fmp['peg'];\n"
    "            $result['roe']            = $fmp['roe'];\n"
    "            $result['roa']            = $fmp['roa'];\n"
    "            if ($fmp['equity_ratio'] > 0) $result['equity_ratio'] = $fmp['equity_ratio'];\n"
    "            if ($fmp['market_cap'] > 0) $result['market_cap'] = $fmp['market_cap'];\n"
    "        } else {\n"
    "            wp_stocks_log('error', 'fmp_ratios', $symbol, 'FMPからの財務指標取得に失敗、Yahoo由来の値にフォールバック');\n"
    "        }\n"
    "\n"
    "        $earnings_dates = wp_stocks_fmp_get_earnings_dates();\n"
    "        if (!empty($earnings_dates[$symbol])) {\n"
    "            $result['earnings_date'] = $earnings_dates[$symbol];\n"
    "        }\n"
    "    }\n"
    "\n"
    "    return $result;\n"
    "}\n"
)

assert content.count(old) == 1, "対象ブロックが見つからないか複数あります"

new = (
    "    $is_us_symbol = (strpos($symbol, '.T') === false);\n"
    "    if ($is_us_symbol) {\n"
    "        $fmp = wp_stocks_fmp_get_ratios($symbol);\n"
    "        if ($fmp !== false) {\n"
    "            $result['per']            = $fmp['per'];\n"
    "            $result['pbr']            = $fmp['pbr'];\n"
    "            $result['eps']            = $fmp['eps'];\n"
    "            $result['profit_margin']  = $fmp['profit_margin'];\n"
    "            $result['dividend_yield'] = $fmp['dividend_yield'];\n"
    "            $result['peg_trailing']   = $fmp['peg_trailing'];\n"
    "            $result['peg']            = $fmp['peg'];\n"
    "            $result['roe']            = $fmp['roe'];\n"
    "            $result['roa']            = $fmp['roa'];\n"
    "            if ($fmp['equity_ratio'] > 0) $result['equity_ratio'] = $fmp['equity_ratio'];\n"
    "            if ($fmp['market_cap'] > 0) $result['market_cap'] = $fmp['market_cap'];\n"
    "        } else {\n"
    "            wp_stocks_log('error', 'fmp_ratios', $symbol, 'FMPからの財務指標取得に失敗、Yahoo由来の値にフォールバック');\n"
    "        }\n"
    "\n"
    "        $earnings_dates = wp_stocks_fmp_get_earnings_dates();\n"
    "        if (!empty($earnings_dates[$symbol])) {\n"
    "            $result['earnings_date'] = $earnings_dates[$symbol];\n"
    "        }\n"
    "    } else {\n"
    "        // 日本株：J-Quantsの予想EPS等でPEG・EPS関連指標を算出（yfinance予想PEG不備の代替）\n"
    "        $jquants_code = str_replace('.T', '', $symbol);\n"
    "        $jquants = wp_stocks_jquants_get_fins_summary($jquants_code);\n"
    "        if ($jquants !== false) {\n"
    "            if ($jquants['forecast_eps'] !== null) $result['forward_eps'] = $jquants['forecast_eps'];\n"
    "            if ($jquants['equity_ratio'] !== null) $result['equity_ratio'] = round($jquants['equity_ratio'] * 100, 1);\n"
    "            if ($jquants['roe'] !== null)           $result['roe']          = round($jquants['roe'] * 100, 1);\n"
    "\n"
    "            // 予想EPS成長率(%) = (来期予想EPS - 当期予想EPS) / 当期予想EPS × 100\n"
    "            if (!empty($jquants['forecast_eps']) && !empty($jquants['next_fy_forecast_eps']) && $jquants['forecast_eps'] > 0) {\n"
    "                $growth_rate = ($jquants['next_fy_forecast_eps'] - $jquants['forecast_eps']) / $jquants['forecast_eps'] * 100;\n"
    "                if ($growth_rate > 0 && $result['forward_per'] > 0) {\n"
    "                    $result['peg'] = round($result['forward_per'] / $growth_rate, 2);\n"
    "                } else {\n"
    "                    $result['peg'] = 0; // 成長率がマイナス/ゼロはPEGとして意味を持たないため非表示扱い\n"
    "                }\n"
    "            }\n"
    "        } else {\n"
    "            wp_stocks_log('error', 'jquants_ratios', $symbol, 'J-Quantsからの財務指標取得に失敗、Yahoo由来の値にフォールバック');\n"
    "        }\n"
    "    }\n"
    "\n"
    "    return $result;\n"
    "}\n"
)

content = content.replace(old, new)
io.open(path, "w", encoding="utf-8").write(content)
print("wp-stocks-manager.php: OK")
